cache:
  - C:\strawberry

install:
  - if not exist "C:\strawberry" choco install strawberryperl -y
  - set PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%
  #  Create the c:\tmp directory because Data::UUID can't be built on Windows without it. (rjbs/Data-UUID#24)
  - mkdir C:\tmp
  - cpanm --quiet --installdeps --with-develop --notest .

build_script:
  - perl Build.Pl
  - perl Build

test_script:
  - perl Build test
